Update build-macos.yml

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -1,4 +1,7 @@
-#!/bin/bash -e
+#!/bin/bash
+
+set -x  # Enable debugging
+set -e  # Exit immediately if a command exits with a non-zero status
 
 name: Build-macos
 
